# Generated by Django 3.0.7 on 2020-08-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("xmltables", "0002_xmlcolumn_col_xsd_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="xmltable",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Determine which model the XMLTABLE query would refer to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AlterField(
            model_name="xmltable",
            name="document_expression",
            field=models.CharField(
                help_text="Provide context for the XMLTABLE query. This will likely be the name of the XML type column or a path to derive data from that column.",
                max_length=256,
            ),
        ),
    ]
